package com.eastdream.eastdream.dao;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbggenerated
     */
    private String menu_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_name
     *
     * @mbggenerated
     */
    private String menu_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_level
     *
     * @mbggenerated
     */
    private Integer menu_level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_menu
     *
     * @mbggenerated
     */
    private String parent_menu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.uuid
     *
     * @return the value of menu.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.uuid
     *
     * @param uuid the value for menu.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbggenerated
     */
    public String getMenu_id() {
        return menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menu_id the value for menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenu_id(String menu_id) {
        this.menu_id = menu_id == null ? null : menu_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_name
     *
     * @return the value of menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenu_name() {
        return menu_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_name
     *
     * @param menu_name the value for menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenu_name(String menu_name) {
        this.menu_name = menu_name == null ? null : menu_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_level
     *
     * @return the value of menu.menu_level
     *
     * @mbggenerated
     */
    public Integer getMenu_level() {
        return menu_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_level
     *
     * @param menu_level the value for menu.menu_level
     *
     * @mbggenerated
     */
    public void setMenu_level(Integer menu_level) {
        this.menu_level = menu_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_menu
     *
     * @return the value of menu.parent_menu
     *
     * @mbggenerated
     */
    public String getParent_menu() {
        return parent_menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_menu
     *
     * @param parent_menu the value for menu.parent_menu
     *
     * @mbggenerated
     */
    public void setParent_menu(String parent_menu) {
        this.parent_menu = parent_menu == null ? null : parent_menu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", menu_id=").append(menu_id);
        sb.append(", menu_name=").append(menu_name);
        sb.append(", menu_level=").append(menu_level);
        sb.append(", parent_menu=").append(parent_menu);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}